import enum

class Event(enum.Enum):
    CANCEL = "CANCEL"

    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    AUTHORIZED = "AUTHORIZED"

    NOTIFICATION_SENT = "NOTIFICATION_SENT"

    ONLINE_DOCUMENTS_SIGNING = "ONLINE_DOCUMENTS_SIGNING"
    COURIER_DOCUMENTS_SIGNING = "COURIER_DOCUMENTS_SIGNING"

    ONLINE_SIGNING_FAILED = "ONLINE_SIGNING_FAILED"
    COURIER_SIGNING_FAILED = "COURIER_SIGNING_FAILED"

    ONLINE_SIGNING_COMPLETED = "ONLINE_SIGNING_COMPLETED"
    COURIER_SIGNING_COMPLETED = "COURIER_SIGNING_COMPLETED"

    MONEY_TRANSFER_IS_READY = "MONEY_TRANSFER_IS_READY"

    MONEY_TRANSFER_COMPLETED = "MONEY_TRANSFER_COMPLETED"
    MONEY_TRANSFER_FAILED = "MONEY_TRANSFER_FAILED"
