import enum

class State(enum.Enum):
    NEW = "NEW"

    CANCELLED = "CANCELLED"
    FAILED = "FAILED"
    COMPLETED = "COMPLETED"

    NOTIFY_FAILED = "NOTIFY_FAILED"
    NOTIFY_CANCELLED = "NOTIFY_CANCELLED"

    AUTHORIZED_APPLICATION = "AUTHORIZED_APPLICATION"
    ONLINE_SIGNING = "ONLINE_SIGNING"
    COURIER_SIGNING = "COURIER_SIGNING"
    SIGNED_APPLICATION = "SIGNED_APPLICATION"
    MONEY_TRANSFERRING = "MONEY_TRANSFERRING"
